p8105_hw2_qz2527.Rmd
================
kindle zhang
2023-10-01

## Problem 1

First, clean the data in `pols-month.csv`. Use `separate()` to break up
the variable `mon` into integer variables `year`, `month`, and `day`;
replace month number with month name; create a `president` variable
taking values `gop` and `dem`, and remove `prez_dem` and `prez_gop`; and
remove the day variable.

``` r
month_df = 
  tibble(
    month_num = 1:12,
    month_abb = month.abb,
    month = month.name
  )

my_data_1 = read.csv("data_file/pols-month.csv") |> 
  janitor::clean_names() |> 
  separate(mon, into = c("year", "month", "day"), "-") |> 
  mutate(
    year = as.numeric(year),
    month = as.numeric(month),
    day = as.numeric(day)) |> 
  mutate(
    month = case_match(
        month,
        01 ~ "January",
        02 ~ "February",
        03 ~ "March",
        04 ~ "April",
        05 ~ "May",
        06 ~ "June",
        07 ~ "July",
        08 ~ "August",
        09 ~ "September",
        10 ~ "October",
        11 ~ "November",
        12 ~ "December",
      )
  ) |> 
  mutate(president = recode(prez_gop, "0" = "dem", "1" = "gop", "2" = "gop")) |> 
  select(year, month, everything(), -day, -starts_with("prez"))
```

Second, clean the data in `snp.csv` using a similar process to the
above. For consistency across datasets, arrange according to year and
month, and organize so that `year` and `month` are the leading columns.

``` r
my_data_2 = 
  read_csv(
    "data_file/snp.csv",
    col_types = cols(date = col_date(format = "%m/%d/%y"))) |> 
  janitor::clean_names() |> 
  separate(date, into = c("year","month_num", "day"), convert = TRUE) |> 
  mutate(year = if_else(year>2023, year-100, year)) |> 
  left_join(x = _, y = month_df) |> 
  select(year, month, close)
```

    ## Joining with `by = join_by(month_num)`

Third, tidy the unemployment data so that it can be merged with the
previous datasets. This process will involve switching from “wide” to
“long” format; ensuring that key variables have the same name; and
ensuring that key variables take the same values.

``` r
my_data_3 = 
  read_csv("./data_file/unemployment.csv") |> 
  rename(year = Year)|> 
  pivot_longer(
    Jan:Dec,
    names_to = "month_abb",
    values_to = "unemployment"
  ) |> 
  left_join(x = _, y = month_df) |> 
  select(year, month, unemployment)
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
    ## Joining with `by = join_by(month_abb)`

Join the datasets by merging `snp` into `pols`, and merging
`unemployment` into the result.

``` r
data_new = 
  left_join(my_data_1, my_data_2) |> 
  left_join(x = _, y = my_data_3)
```

    ## Joining with `by = join_by(year, month)`
    ## Joining with `by = join_by(year, month)`

``` r
str(data_new)
```

    ## 'data.frame':    822 obs. of  11 variables:
    ##  $ year        : num  1947 1947 1947 1947 1947 ...
    ##  $ month       : chr  "January" "February" "March" "April" ...
    ##  $ gov_gop     : int  23 23 23 23 23 23 23 23 23 23 ...
    ##  $ sen_gop     : int  51 51 51 51 51 51 51 51 51 51 ...
    ##  $ rep_gop     : int  253 253 253 253 253 253 253 253 253 253 ...
    ##  $ gov_dem     : int  23 23 23 23 23 23 23 23 23 23 ...
    ##  $ sen_dem     : int  45 45 45 45 45 45 45 45 45 45 ...
    ##  $ rep_dem     : int  198 198 198 198 198 198 198 198 198 198 ...
    ##  $ president   : chr  "dem" "dem" "dem" "dem" ...
    ##  $ close       : num  NA NA NA NA NA NA NA NA NA NA ...
    ##  $ unemployment: num  NA NA NA NA NA NA NA NA NA NA ...

Let’s talk about the 538 data_new. The `my_data_1` data has 822
observations and 9 variables and tells us about the party affiliation
distribution (democrat or republican) for governors and senators for a
given year from years 1947 to 2015. It also tells us whether the sitting
president was a democrat or republican. The `my_data_2` data has 787
observations and 3 variables, ranging from years 1950 to 2015. The
`my_data_3` data has 816 observations and 3 variables ranging from years
1948 to 2015. In Januarys in or after 1975 in which a democrat was
president, the **average unemployment rate was 6.57**. The average
unemployment rate over the same time period in which a republican was
president was 6.47.

## Problem 2

Read and clean the Mr. Trash Wheel sheet: \* specify the sheet in the
Excel file and to omit non-data entries (rows with notes / figures;
columns containing notes) using arguments in `read_excel` \* use
reasonable variable names \* omit rows that do not include
dumpster-specific data

``` r
library(readxl)
```

``` r
data_tw = 
  read_excel("./data_file/202309_tw.xlsx", 
             sheet = "Mr. Trash Wheel",
             range = "A2:M586") |> 
  janitor::clean_names() |> 
  filter(!is.na(dumpster)) |> 
  mutate(
    year = as.numeric(year)
  )
```

The data include a column for the (approximate) number of homes powered.
This calculation is described in the `Homes powered note`, but not
applied to every row in the dataset. Update the data to include a new
`homes_powered` variable based on this calculation.

``` r
data_tw = 
mutate(
  data_tw,
  homes_powered = (weight_tons * 500) / 30
  )
```

Use a similar process to import, clean, and organize the data for
Professor Trash Wheel and Gwynnda, and combine these with the Mr. Trash
Wheel dataset to produce a single tidy dataset. To keep track of which
Trash Wheel is which, you may need to add an additional variable to all
datasets before combining.

``` r
data_ptw = 
  read_excel("./data_file/202309_tw.xlsx", 
             sheet = "Professor Trash Wheel",
             range = "A2:L108") |> 
  janitor::clean_names() |> 
  filter(!is.na(dumpster)) |> 
  mutate(homes_powered = (weight_tons * 500) / 30)

data_gtw = 
  read_excel("./data_file/202309_tw.xlsx", 
             sheet = "Gwynnda Trash Wheel",
             range = "A2:K157") |> 
  janitor::clean_names() |> 
  filter(!is.na(dumpster)) |> 
  mutate(homes_powered = (weight_tons * 500) / 30)
```

``` r
data_tw = 
  mutate(
    data_tw,
    trash_wheel_kind = "Mr. Trash Wheel"
  )

data_ptw = 
  mutate(
    data_ptw,
    trash_wheel_kind = "Professor Trash Wheel"
  )

data_gtw = 
  mutate(
    data_gtw,
    trash_wheel_kind = "Gwynnda Trash Wheel"
  )
data_tw_all = 
  bind_rows(data_tw, data_ptw, data_gtw)

str(data_tw_all)
```

    ## tibble [845 × 15] (S3: tbl_df/tbl/data.frame)
    ##  $ dumpster          : num [1:845] 1 2 3 4 5 6 7 8 9 10 ...
    ##  $ month             : chr [1:845] "May" "May" "May" "May" ...
    ##  $ year              : num [1:845] 2014 2014 2014 2014 2014 ...
    ##  $ date              : POSIXct[1:845], format: "2014-05-16" "2014-05-16" ...
    ##  $ weight_tons       : num [1:845] 4.31 2.74 3.45 3.1 4.06 2.71 1.91 3.7 2.52 3.76 ...
    ##  $ volume_cubic_yards: num [1:845] 18 13 15 15 18 13 8 16 14 18 ...
    ##  $ plastic_bottles   : num [1:845] 1450 1120 2450 2380 980 1430 910 3580 2400 1340 ...
    ##  $ polystyrene       : num [1:845] 1820 1030 3100 2730 870 2140 1090 4310 2790 1730 ...
    ##  $ cigarette_butts   : num [1:845] 126000 91000 105000 100000 120000 90000 56000 112000 98000 130000 ...
    ##  $ glass_bottles     : num [1:845] 72 42 50 52 72 46 32 58 49 75 ...
    ##  $ plastic_bags      : num [1:845] 584 496 1080 896 368 ...
    ##  $ wrappers          : num [1:845] 1162 874 2032 1971 753 ...
    ##  $ sports_balls      : num [1:845] 7.2 5.2 6 6 7.2 5.2 3.2 6.4 5.6 7.2 ...
    ##  $ homes_powered     : num [1:845] 71.8 45.7 57.5 51.7 67.7 ...
    ##  $ trash_wheel_kind  : chr [1:845] "Mr. Trash Wheel" "Mr. Trash Wheel" "Mr. Trash Wheel" "Mr. Trash Wheel" ...

Write a paragraph about these data; you are encouraged to use inline R.
Be sure to note the number of observations in the resulting dataset, and
give examples of key variables. For available data, what was the total
weight of trash collected by Professor Trash Wheel? What was the total
number of cigarette butts collected by Gwynnda in July of 2021?

Let’s talk about the data_tw_all. The `data_tw` data has 584
observations and 15 variables and tells us about the information on the
dumpter number, date of collection, amount of total litter and litter
type for a given year from years 2014 to 2023. It also tells us the
homes powered. The `data_ptw` data has 106 observations and 14
variables, ranging from years 2017 to 2023. The `data_gtw` data has 155
observations and 13 variables ranging from years 2021 to 2023.

The total weight of trash collected by Professor Trash Wheel is 216.26
tons. The total number of cigarette butts collected by Gwynnda in July
of 2021 is 1.63^{4}
